// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgrwtqphjzxmrqqgobqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impncnd0cXBoanp4bXJxcWdvYnFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwOTQ4NTEsImV4cCI6MjA2MzY3MDg1MX0.7Sqf6buxYQLwsswTIrxbGbQ4kEkeyQeztGGDy6-Jmgo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);